// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVAJEyDcnyQT9uuxamMPLJQnmIJc4ev8w',
    appId: '1:138063546463:web:a8585d73ae13c328e9b3ea',
    messagingSenderId: '138063546463',
    projectId: 'bento-web-app-d161f',
    authDomain: 'bento-web-app-d161f.firebaseapp.com',
    storageBucket: 'bento-web-app-d161f.appspot.com',
    measurementId: 'G-QW1X6SWN4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4d7Azn678LJ29OCmsGF2Nvt5MaAAZHXk',
    appId: '1:138063546463:android:6090720ce0f0ced6e9b3ea',
    messagingSenderId: '138063546463',
    projectId: 'bento-web-app-d161f',
    storageBucket: 'bento-web-app-d161f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWqRJXw8gElJ3rqCcyTnWJphMtAr3EJU4',
    appId: '1:138063546463:ios:2aa15f8215333e82e9b3ea',
    messagingSenderId: '138063546463',
    projectId: 'bento-web-app-d161f',
    storageBucket: 'bento-web-app-d161f.appspot.com',
    iosBundleId: 'com.zeepalm.bento',
  );
}
